### ISSUE TITLE
Textile syntax support (or standalone Textile version)

### ISSUE THREAD

**Issue by philwareham** [sparksuite/simplemde-markdown-editor#132]
Love the look of this script - how feasible would it be to make it support Textile syntax as an alternative to Markdown? Or is it too intrinsically tied to markdown.

I work on Textpattern CMS and we need to support both syntaxes, but would be interested in an integration. Might be able to pay some money to make that happen.

**Comment by WesCossick** [comment]
Thanks, glad you like it! So Markdown is pretty heavily tied into SimpleMDE (which is, after all, short for Simple Markdown Editor). CodeMirror does the parsing while editing, and marked does the rendering for the preview.

Theoretically, you could change CodeMirror's mode to [Textile mode](https://codemirror.net/mode/textile/index.html), and swap marked out with a JS textile parser. However, you'd also need to update all of the functionality for the shortcuts, toolbar buttons, etc. to use Textile syntax rather than Markdown syntax. Then you'd also have to update the stylesheets to make sure everything looked proper visually.

Unfortunately, this is a very specific interest that's beyond the scope of SimpleMDE, which focuses exclusively on Markdown. I wouldn't have the time to make these changes to SimpleMDE to turn it into a separate Textile editor. But hopefully you or someone on your team can accomplish this.

**Comment by philwareham** [comment]
OK, thanks for the response. I will think about a fork, maybe. Cheers!

**Comment by appel** [comment]
> OK, thanks for the response. I will think about a fork, maybe. Cheers!

Sorry to reopen an old and closed thread, but I would be really interested in Textile support for SimpleMDE. @philwareham, did you ever attempt a fork by chance?

**Comment by philwareham** [comment]
Sorry I didn't go any further with a Textile version. It's still something I'd been keen on though. Maybe raise an issue at Textpattern project (which is where I was hoping to use it) and see if anyone is keen on doing the work: https://github.com/textpattern/textpattern/issues
