### ISSUE TITLE
Please don't use font-face for the icons

### ISSUE THREAD

**Issue by anhtran** [sparksuite/simplemde-markdown-editor#187]
I worked with many online editors and always feel heavy when they load fonts for the icons. I recommend using SVG for the replacement. Just few icons on stage, we don't need load all of them.

http://ianfeather.co.uk/ten-reasons-we-switched-from-an-icon-font-to-svg/
https://www.google.com/design/icons/

**Comment by WesCossick** [comment]
Sorry, but this one's staying. Many websites that would utilize a Markdown editor already use Font Awesome, so it'd actually be less efficient to load separate SVG icons. Secondly, the performance hit is rather minimal since it's served by a very fast CDN and it's aggressively cached. Finally, any performance efficiency gained is seriously outweighed by the developer inefficiency involved with creating and maintaining SVG icons.

**Comment by FabianKoestring** [comment]
Ability to define own icons would be nice. We just changed the icons on our whole page from [Font-Awesome](https://github.com/FortAwesome/Font-Awesome) to [material-design-icons](https://github.com/google/material-design-icons).

In my project FontAwesome gets loaded only to make this module work.

**Comment by WesCossick** [comment]
In the options, you can set `autoDownloadFontAwesome` to `false`, then give each icon in the toolbar it's own class using the toolbar option...

``` js
// Customize all information and/or add your own icons
var simplemde = new SimpleMDE({
    toolbar: [{
            name: "bold",
            action: SimpleMDE.toggleBold,
            className: "fa fa-bold",
            title: "Bold (Ctrl+B)",
        },
        "|", // Separator
        ...
    ],
});
```

...then you can style each icon however you please with custom CSS.

**Comment by manuel-reil** [comment]
@FabianKoestring How have you achieved using material-design-icons? As for material-design-icons the name of the icon is not in the css class, but between the HTML elements.
