### ISSUE TITLE
Help button with info about markdown

### ISSUE THREAD

**Issue by fraserredmond** [sparksuite/simplemde-markdown-editor#19]
Most users won't have heard of markdown, and might need some help with how to use it.

I'd suggest a help (question-mark?) button on the toolbar that opens http://markdowntutorial.com/ in a new tab.

**Comment by WesCossick** [comment]
Where we're using SimpleMDE, we've written a Markdown guide via a nearby link to a new page on the same website. That way, the style matches, they don't visit a third party website, and we don't have to worry about whether or not that third party website is still online.

For these reasons, if a help button is added, I'd like for it to display a guide on the same page, probably in a popup window of sorts.

**Comment by fraserredmond** [comment]
Fair enough on showing your own guide - though maybe the url could be configured with that as the default?

Could be worth keeping an eye on the result of this, whenever it gets published: http://blog.codinghorror.com/toward-a-better-markdown-tutorial/

I would have thought a new tab was the simplest, most reliable option - popups built on the page in html would clash with style (and maybe js), browser popups sometimes get blocked.

**Comment by WesCossick** [comment]
That might actually be best- a configurable URL. I like to maintain a high standard of consistency and customization, so I personally would choose to use a custom page. But a standard guide as the default URL would work well for others.

While Jeff Atwood has a good idea, I would argue that an interactive guide is less so a guide, and more so a tutorial. The help button should probably link to something that is just a quick reference point rather than a full-blown tutorial.

After a cursory Google search, the best I could find was https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet. But linking to GitHub is bound to confuse a non-technical user. What about writing a cheat sheet with minimal styling (so as to not conflict with the embedding websites' styles) and no links, and placing it on the SimpleMDE GitHub pages site that's currently hosting the demo?

**Comment by fraserredmond** [comment]
I think the argument for Jeff Atwood's version (whenever it arrives) is it's likely to become the standard markdown tutorial/reference - which is what his aim is, and what we'd want to use in this case.

In the mean time, that cheatsheet looks good, and I agree hosting a prettier version yourself will be less confusing.

**Comment by WesCossick** [comment]
A simple, generic Markdown guide designed to not conflict with the design of a referring website has been created at http://nextstepwebs.github.io/simplemde-markdown-editor/markdown-guide. Next I'll need to add a help button to the toolbar.

**Comment by WesCossick** [comment]
Done.
