### ISSUE TITLE
Erratic behaviour when preview rendered on server side

### ISSUE THREAD

**Issue by aruizca** [sparksuite/simplemde-markdown-editor#194]
Hi there,
I recently override the `previewRender` function like this:

``` javascript
        previewRender: function(plainText, preview) {
          $.post("/misc/preview",{data: plainText}, function (html) {
            preview.innerHTML = html;
          });
        },
```

when the markdown document is big enough to make the vertical scrollbar appear, when I scroll down/up or modify the document, the preview gets blank and even the content goes blank until I move the scrollbar. It is a very random behaviour to explain accurately, but I guess that's more or less what happens.

I had to revert back the changes and continue rendering on client. While the markdown final display is rendered on server.

Cheers

**Comment by WesCossick** [comment]
Can you setup a jsFiddle that replicates this? Also, what browser and OS are you using, or does it appear to behave the same in every browser?

**Comment by aruizca** [comment]
Hi @WesCossick 
The problem is that you need a server backend. In my case I have a node.js app using marked.js to parse the markdown content.
It was happening in both firefox and chrome. The node.js backend was running on Node.js 4.2.1 on Mac Osx 10.10.5 using Express.js 4.10.6

**Comment by WesCossick** [comment]
Can you create a test file to post to, and set up jsFiddle to use your server's URL? I have a feeling this might be hard to debug without being able to reproduce the error.

**Comment by aruizca** [comment]
I'll try to set something up when I have the chance. Thanks!

**Comment by alexwenzel** [comment]
i can confirm this behaviour. when I render on server side, the editor starts flickering (when i try to scroll down). this makes the preview unuseable.

**Comment by WesCossick** [comment]
@alexwenzel To reopen this issue, you'll need to be able to present a replicable example using jsFiddle.

**Comment by Steve-Mcl** [comment]
Hi I suspect the issue is still present & it seems to be related to `previewRender`.  In particular the async version.

In my particular instance, I am not using a server based renderer (but as fair as SimpleMDE is concerned, it may as well be)

Demo1 - Scrolling via PAGE DOWN and PAGE UP. What you will see 
![pagedownpageup](https://user-images.githubusercontent.com/44235289/66324789-05605200-e91e-11e9-952a-a130eca56e2b.gif)


Demo2 - Editing using keyboard only.  What you will see is 
* scrolling issue
* sometimes the editor goes blank 
* sometimes the carrot will not align correctly to text
![editing-preview-issues](https://user-images.githubusercontent.com/44235289/66324797-098c6f80-e91e-11e9-8eb1-5069ddde7f7b.gif)


I have created a jsfiddle for you to inspect.
https://jsfiddle.net/0n1s3Ldb/2/ 

_NOTE: The `sync` version doesn't appear to have these issues..._
https://jsfiddle.net/xsd6gbv2/  


notes: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
OS: Windows 7
