### ISSUE TITLE
"Embed" video feature

### ISSUE THREAD

**Issue by JamieWohletz** [sparksuite/simplemde-markdown-editor#225]
I was thinking that it would be pretty cool to be able to embed YouTube videos in some rudimentary way (YouTube only because it's extremely common and has an easy-to-use API -- future video services could be implemented in the future).

I'm not really sure how this feature should work, though. The way I see it, there are **two options**:
1. Toolbar button that generates [markdown like this](http://stackoverflow.com/a/29862668/2069194).
2. True embeds, where you can play the video right on the page. To do this and make it consistent with the rest of the editor, we would probably want to introduce a bit of custom markdown specifically for video embeds. Something like `$[My cool video](https://youtube.com/myvideoid)`. We could have a toolbar button that generates this stuff too. 
   This is the route I'd prefer to take, because you really don't want your users to leave your site for YouTube whenever they view a video. 

I'm willing to make a PR to implement this feature, but I need some thoughts first. 

Plausible? Stupid? Unnecessary? Too vulnerable to XSS attacks? Let me know!

**Comment by WesCossick** [comment]
SimpleMDE aims to be a super easy-to-use editor for stock Markdown. Right now there's no support for custom markup, but [it's been proposed before](https://github.com/NextStepWebs/simplemde-markdown-editor/issues/57). I wouldn't consider adding a dedicated YouTube button to the editor, because that's outside the scope of what SimpleMDE aims to achieve. Plus the majority of SimpleMDE users wouldn't take advantage of it. However, if you're interested in taking up the task of supporting custom markup, it'd be a much appreciated PR and can be used in conjunction with a [custom toolbar icon](https://github.com/NextStepWebs/simplemde-markdown-editor#toolbar-icons) that you'd create for your website to insert the custom markup.

**Comment by aruizca** [comment]
Something like the MDWIKI gimmicks would be awesome:
http://dynalon.github.io/mdwiki/#!gimmicks.md

**Comment by JamieWohletz** [comment]
@WesCossick Thanks for the answer! Just to be sure I understood you, you mean extending SimpleMDE to support any type of custom markup that can be inserted via custom toolbar buttons? 

Also, @aruizca thanks for the link! I'll take that into consideration should I decide to take this on.

**Comment by WesCossick** [comment]
@JamieWohletz The PR would be for a very user friendly way of supporting custom markup. Honestly, it's something that's so broad, it'd be very difficult to make as easy as it'd need to be for it to be considered as a new option for SimpleMDE. There are so many types of markups, whether the line starts with certain characters, text is wrapped in specific characters, text is followed by or preceded by certain symbols, etc. Then the editing rendering would need to apply some kind of styling, as would the preview rendering.

For these reasons, custom markup is likely something that would necessarily have to be implemented by the developer for his/her own needs. As I see it, a simple option would be too restrictive for it to be useful to anyone, and a complex option would be too difficult for it to be included in SimpleMDE.

Unless you have a very clever method of accomplishing this, I'd say you're better off building this functionality into your own implementation of SimpleMDE.

**Comment by antranpk** [comment]
`dfgadfgdsfgsdfg`
