### ISSUE TITLE
Duplicate heading text produces duplicate id attributes in HTML output

### ISSUE THREAD

**Issue by iainsimmons** [sparksuite/simplemde-markdown-editor#282]
If you have multiple headings with the same text for whatever reason, the corresponding heading tags will also have the same `id` attribute. They can also conflict with other elements on the page.

Input:

``` md
# Example
## Example
```

Output:

``` html
<h1 id="example">Example</h1>
<h2 id="example">Example</h2>
```

I'd suggest both prefixing the IDs with something to sort of namespace them (e.g. `mde-h1`) and possibly suffixing with an incrementing integer (either for any duplicate headings, or globally for all headings).

Suggested Output:

``` html
<h1 id="mde-h1--example--1">Example</h1>
<h2 id="mde-h2--example--2">Example</h2>
```

**Comment by WesCossick** [comment]
This must be a setting with [marked](https://github.com/chjj/marked). Not sure if it's configurable.

**Comment by TatzyXY** [comment]
I am not sure if this will help you guys but I just post my investigations about this issue here:
I installed the package via bower so I got all files to debug a bit arround.
The problem is the following function in the file `simplemd.js`:

```
Renderer.prototype.heading = function(text, level, raw) {
  return '<h'
    + level
    + ' id="'
    + this.options.headerPrefix
    + raw.toLowerCase().replace(/[^\w]+/g, '-')
    + '">'
    + text
    + '</h'
    + level
    + '>\n';
};
```

it seems that this function comes from [marked](https://github.com/chjj/marked) as @WesCossick already said.

To "fix" that bug just replace the function by the following code:

```
Renderer.prototype.heading = function(text, level, raw) {
  return '<h'
    + level
    + '>'
    + text
    + '</h'
    + level
    + '>\n';
};
```

I am not familiar with this modules so I dont know if that has any side effects but it works for me. I hope my post will push one of the developers who are familiar with this entire Library into a direction that helps. I hope for a fix, then I can remove my dirty hack ;)

I think the ids are used for a special feature but I dont know which function needs that ids. At the moment I dont have any errors when I just remove them...

**Comment by danabrey** [comment]
Without looking at the code, `this.options.headerPrefix` looks possibly useful.

**Comment by TatzyXY** [comment]
> Without looking at the code, this.options.headerPrefix looks possibly useful.
> `this.options.headerPrefix` is already set to nothing at default.

if you would set a `this.options.headerPrefix` the output just results in something like this.

```
<h1 id="myheaderPrefix-test">Test</h1>
<h2 id="myheaderPrefix-test">Test</h2>
```

This would still not turn off any duplicate ids in the output ;)

**Comment by WesCossick** [comment]
@TatzyXY it definitely looks like this is coming from marked. I would recommend submitting a PR on their repository so that it eventually makes its way into SimpleMDE.
