### ISSUE TITLE
WYSIWYG editing from the preview button

### ISSUE THREAD

**Issue by aguynamedben** [sparksuite/simplemde-markdown-editor#442]
Hi, this editor is beautiful and we're probably going to use it either way. Thanks for your work on this project.

I was wondering if there was an option I was missing somewhere that allows WYSIWYG editing from the preview state? It doesn't seem like many Markdown editors support this, and I'm not sure why. Ideally, I'd like my business users to not know that they were editing Markdown.

I'm no just missing an option somewhere to set the default view to WYSIWYG, right?

**Comment by scottromack** [comment]
Totally agree, this should not be that hard unless I am missing something.. I want to store cms content as a string then render to html at runtime...

**Comment by aguynamedben** [comment]
@ShaggyDude FYI if all you just want to do is render Markdown on a page for viewing, you can use Markdown renderers like [redcarpet](https://github.com/vmg/redcarpet). It'd be nice to be able to edit the previewed rendering of Markdown in simplemde, though.

**Comment by WesCossick** [comment]
Duplicate of #319, #302, #281, #232, and #422

**Comment by aguynamedben** [comment]
@WesCossick Just to make sure, is [this](https://github.com/NextStepWebs/simplemde-markdown-editor/issues/281#issuecomment-198509480) the answer?

> This is not possible. Similar concepts have been tried, but with the way CodeMirror functions, they do not result in a well polished end product.

Is CodeMirror the best example of this being possible? The only example of this concept working I found was [woofmark](https://bevacqua.github.io/woofmark/). And I think [medium-editor](https://github.com/yabwe/medium-editor).

Are there fundamental reason this can't be done? (I realize it might be beyond the scope of simplemde for now, but curious, it seems like if somebody could nail it it'd be valuable)

**Comment by WesCossick** [comment]
CodeMirror is the project that powers SimpleMDE behind the scenes. It's the backbone. Trying to hide the Markdown syntax does not work because CodeMirror does not function well when some of the syntax is hidden.

Editing a Markdown document without the Markdown syntax would be counter-intuitive. Markdown is designed to be "publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions." Therefore, this is not the goal of SimpleMDE, whose job is to make writing Markdown syntax even more understandable and intuitive for beginners and experts alike.

If you want an editor that edits a document without showing the syntax, you may want to look into an typical HTML text editor, since Markdown would not even be necessary at that point. In fact, Markdown would only limit the writer's formatting options.

**Comment by aguynamedben** [comment]
@WesCossick Thanks for sharing your stance on this. I don't think the stated goal that Markdown "should be publishable as-is, as plain text" precludes or invalidates a WYSIWYG editor for Markdown, or that it would be counter-intuitive to use one, but I respect your opinion on this.

We're using SimpleMDE and it's great. Thanks for your work on this.
