### ISSUE TITLE
Text selection on mobile devices (IOS / Android) broken

### ISSUE THREAD

**Issue by MoBe80** [sparksuite/simplemde-markdown-editor#514]
When you try to select text on a mobile device the selectionmarkers will disappear after a few characters.

Tested on a LG G5 (Android 6) and a iPad Air 2 on IOS 10 with touch and a hardware keyboard.

**Comment by stephenoakman** [comment]
I'm also hitting this issue. After looking into it more, the issue seems to be with codemirror. In particular there is a function updateLineText (in codemirror/src/display/update_line.js) which replaces the current line with formatted html which contains a the current selection wrapped in a span so it can apply a css class for a selected text style. It does this by replacing the current node with a new node with the span applied.

Since the existing node may just be a text node, it can't just slice it up so is forced to do the replaceChild call. This is what then resets the selection so it is lost on a mobile device.

I've been looking at how feasible it would be to change codemirror so on a mobile device it didn't replace the node but it has quite a lot of knock on effects so I've not made much progress at the moment, but hopefully this will give a starting point for others that may be interested.

**Comment by stephenoakman** [comment]
After looking further, the fix is as simple as passing styleSelectedText: false as one of the options when initialising SimpleMDE

**Comment by WesCossick** [comment]
@stephenoakman Would you mind submitting a PR with this fix and a demonstration of the before/after?

**Comment by MoBe80** [comment]
@stephenoakman thanks for your investigation, works perfekt for me on iOS and Android.
