### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by knzudgt** [sparksuite/simplemde-markdown-editor#579]
I tried to install `simplemde` but I receive the following error:

```
elrond@IMLADRIS:~$ npm install simplemde --save
npm WARN saveError ENOENT: no such file or directory, open '/home/elrond/package.json'
/home/elrond
└─┬ simplemde@1.11.2 
  ├── codemirror@5.25.2 
  ├─┬ codemirror-spell-checker@1.1.2 
  │ └── typo-js@1.0.3 
  └── marked@0.3.6 

npm WARN enoent ENOENT: no such file or directory, open '/home/elrond/package.json'
npm WARN elrond No description
npm WARN elrond No repository field.
npm WARN elrond No README data
npm WARN elrond No license field.
```

**Comment by danabrey** [comment]
This looks like a problem specific to your filesystem. Does the same thing happen when you try to install and `--save` other packages? 

Make sure that the file permissions of `package.json` look right (correct owner, with read/write access etc.)

**Comment by knzudgt** [comment]
@danabrey It would be the first package I install.
I am on a Ubuntu 14.04 LTS machine.
I installed `Node.js` via package manager following [instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) in the official `Node.js` web page:

    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    sudo apt-get install -y nodejs

Then I tried to install `simplemde` as I explained before and got the above error messages.

**Comment by danabrey** [comment]
@knzudgt Ah, no worries. npm is complaining that it can't find a `package.json` file, which is what npm uses to save information about your project and what packages it depends on. If you want to `--save` a package to your project, you'll need to create a `package.json` for your project. The easiest way to do this is to run `npm init -y` on the command line from your project directory.

Take a look here for a guide to package.json: https://docs.npmjs.com/getting-started/using-a-package.json

**Comment by knzudgt** [comment]
@danabrey sorry for the dumb question: am I required to create a project in order to use `simplemde`? In other words, is `simplemde` meant to be a piece of a larger project and not a stand alone application?

**Comment by danabrey** [comment]
@knzudgt No worries at all, there are no dumb questions. SimpleMDE is supposed to be used as part of a project, not a standalone thing.

By 'project' I just mean whatever you're aiming to use SimpleMDE for. If you want to use npm and save a reference to the dependency on SimpleMDE, you'll need a `package.json`.

If you just want to use SimpleMDE on a web page, you can alternatively just include the JS/CSS in the page, via the instructions in the README:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
```

npm and Bower are package managers, which allow you to explicitly declare your project's depedencies, and keep them out of your codebase and version control. They are a solution to the problems caused by the old way of downloading `simplemde.js` and adding it to your project's version control etc. I would very much recommend having a cursory read of the npm docs.
