### ISSUE TITLE
Number sub-lists issue?

### ISSUE THREAD

**Issue by jesseleite** [sparksuite/simplemde-markdown-editor#74]
Is this an issue with numbered sub-list handling in the editor view (notice the numbering inconsitency between editor and preview)?

![example](http://g.recordit.co/zQP5sHO3XN.gif)

**Comment by WesCossick** [comment]
This is just Markdown's parsing strategy. It ignores all numbers and replaces them with the correct ones. A list like this is fine:

```
1. Test
1. Test
    1. Test
    1. Test
1. Test
```

It would be rather complex for the editor to dynamically and recursively change the numbers every time a tab was pressed on a list, or a new bullet point added, since it's all just plain text. Therefore, the editor does not make the attempt.

**Comment by jesseleite** [comment]
Fair enough :P  Sorry for brining up all these issues, don't mean to be a bother.
