### ISSUE TITLE
Editing in preview mode

### ISSUE THREAD

**Issue by mikeerickson** [sparksuite/simplemde-markdown-editor#812]
Is it possible to edit documents in preview mode.  So far as I can tell, when in preview mode, the document is read only.

**Comment by Gigamick** [comment]
Looks like this project isn't supported anymore but yeah, this is a deal breaker for me.

The users of my app aren't tech savvy (I had one customer complaint because they didn't know what "copied to clipboard" meant) and if they see asterisks and underscores appearing in their copy they will think it's broken.

**Comment by mikeerickson** [comment]
@GigaMick well, I guess will mark this one off my list.  I am looking at EasyMD but it has been a real PITA getting integrated into a VueJS app.

**Comment by Gigamick** [comment]
> @GigaMick well, I guess will mark this one off my list. I am looking at EasyMD but it has been a real PITA getting integrated into a VueJS app.

@mikeerickson cheers for the tip. I'll check it out and see how I get integrating it into a straight up Laravel app.
